{
 "title": "Overview of all tests",
 "description": "Overview of all tests",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "profile",
    "label": "Profile",
    "query": "SELECT DISTINCT profile_name FROM jmresults_statistic"
   },
   {
    "name": "runid",
    "label": "RunId",
    "query": "SELECT DISTINCT run_id FROM jmresults_statistic where profile_name ='$profile'"
   },
   { "name": "sampler_type", "label": "Sampler type ", "query": "REQUEST,TRANSACTION" },
   { "name": "agr", "label": "Aggregation", "query": "1,10,60,1800,3600" }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    now() as t,\n    avg(average_time),\n    run_id\nFROM jmresults_statistic\n\nWHERE\n    sampler_type = '$sampler_type'\n    AND profile_name = '$profile'\nGROUP BY run_id\n\nORDER BY run_id ASC\n",
     "rawQuery": "SELECT\n    now() as t,\n    avg(average_time),\n    run_id\nFROM jmresults_statistic\n\nWHERE\n    sampler_type = 'REQUEST'\n    AND profile_name = 'TEST'\nGROUP BY run_id\n\nORDER BY run_id ASC",
     "round": "0s",
     "table": "jmresults"
    }
   ]
  },
  {
   "title": "Median response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    now() as t,\n    median(average_time),\n    run_id\nFROM jmresults_statistic\nWHERE sampler_type = '$sampler_type'\nAND profile_name ='$profile'\nGROUP BY run_id\nORDER BY run_id ASC",
     "rawQuery": "SELECT\n    now() as t,\n    median(average_time),\n    run_id\nFROM jmresults_statistic\nWHERE sampler_type = 'REQUEST'\nAND profile_name ='TEST'\nGROUP BY run_id\nORDER BY run_id ASC",
     "round": "0s",
     "table": "jmresults"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT sample_label,\n       sum(points_count) as \"Total\",\n       count(points_count) as \"TotalRecs\",\n       sum(points_count)/count(points_count) as \"Compress\",\n       avg(average_time)/1000 as \"AvgResp\",\n       min(average_time)/1000 as \"MinResp\",\n       max(average_time)/1000 as \"MaxResp\",\n       quantile(0.9)(average_time) as \"90perc\",\n       quantile(0.95)(average_time) as \"95perc\",\n       quantile(0.97)(average_time) as \"97perc\",\n       quantile(0.99)(average_time) as \"99perc\",\n       sum(errors_count) as \"Errors\",\n       (sum(errors_count)/sum(points_count)) as \"ErrorRate\"\nfrom jmresults\nWHERE  profile_name ='TEST' and run_id='TEST'\nGROUP BY sample_label;",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT run_id,\n       count(timestamp_sec) as total,\n       min(timestamp_sec) as start,\n       max(timestamp_sec) as stop,\n       total/toUInt64(stop-start) as rate,\n       avg(average_time)/1000 as \"AvgResp\",\n       median(average_time)/1000 as \"MedianResp\",\n       quantileTDigest(0.9)(average_time)/1000 as \"90perc\",\n       quantileTDigest(0.95)(average_time)/1000 as \"95perc\",\n       sum(errors_count) as \"Errors\",\n       (sum(errors_count)/count(timestamp_sec)) as \"ErrorRate\"\nfrom jmresults_statistic\nWHERE  $timeFilter AND profile_name ='$profile' and run_id IN ($runid) and not like(sample_label, 'http%') and sampler_type = '$sampler_type'\nGROUP BY run_id",
     "rawQuery": "SELECT run_id,\n       count(timestamp_sec) as total,\n       min(timestamp_sec) as start,\n       max(timestamp_sec) as stop,\n       total/toUInt64(stop-start) as rate,\n       avg(average_time)/1000 as \"AvgResp\",\n       median(average_time)/1000 as \"MedianResp\",\n       quantileTDigest(0.9)(average_time)/1000 as \"90perc\",\n       quantileTDigest(0.95)(average_time)/1000 as \"95perc\",\n       sum(errors_count) as \"Errors\",\n       (sum(errors_count)/count(timestamp_sec)) as \"ErrorRate\"\nfrom jmresults_statistic\nWHERE  timestamp_sec >= toDateTime(1608026806) AND profile_name ='TEST' and run_id IN ('R002','R001') and not like(sample_label, 'http%') and sampler_type = 'REQUEST'\nGROUP BY run_id",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "jmresults"
    }
   ]
  }
 ]
}